import type { Person, KarajahData, RelResult, Stats } from './types'

const raw: Omit<Person, "monogramAr" | "monogramEn">[] = [
  {
    id: "g0-1",
    gen: 0,
    fatherId: null,
    nameAr: "ناصر",
    nameEn: "Nasser",
    firstAr: "ناصر",
    firstEn: "Nasser",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g1-1",
    gen: 1,
    fatherId: "g0-1",
    nameAr: "جودة ناصر",
    nameEn: "Jawda Nasser",
    firstAr: "جودة",
    firstEn: "Joud",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g1-2",
    gen: 1,
    fatherId: "g0-1",
    nameAr: "ذاكر ناصر",
    nameEn: "Thaker Nasser",
    firstAr: "ذاكر",
    firstEn: "Thaker",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g2-1",
    gen: 2,
    fatherId: "g1-1",
    nameAr: "مصطفى جودة",
    nameEn: "Mustafa Joud",
    firstAr: "مصطفى",
    firstEn: "Mustafa",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g2-2",
    gen: 2,
    fatherId: "g1-1",
    nameAr: "ناصر جودة",
    nameEn: "Nasser Joud",
    firstAr: "ناصر",
    firstEn: "Nasser",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g2-3",
    gen: 2,
    fatherId: "g1-1",
    nameAr: "أحمد جودة",
    nameEn: "Ahmad Joud",
    firstAr: "أحمد",
    firstEn: "Ahmad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g2-4",
    gen: 2,
    fatherId: "g1-1",
    nameAr: "طه جودة",
    nameEn: "Taha Joud",
    firstAr: "طه",
    firstEn: "Taha",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g2-5",
    gen: 2,
    fatherId: "g1-2",
    nameAr: "الهودلي ذاكر",
    nameEn: "Al-Hawdli Thaker",
    firstAr: "الهودلي",
    firstEn: "Al-Hawdli",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g2-6",
    gen: 2,
    fatherId: "g1-2",
    nameAr: "معروف ذاكر",
    nameEn: "Maarouf Thaker",
    firstAr: "معروف",
    firstEn: "Maarouf",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g3-1",
    gen: 3,
    fatherId: "g2-1",
    nameAr: "محمد مصطفى",
    nameEn: "Muhammad Mustafa",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g3-2",
    gen: 3,
    fatherId: "g2-1",
    nameAr: "عبدالله مصطفى",
    nameEn: "Abdullah Mustafa",
    firstAr: "عبدالله",
    firstEn: "Abdullah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g3-3",
    gen: 3,
    fatherId: "g2-1",
    nameAr: "محمود مصطفى",
    nameEn: "Mahmoud Mustafa",
    firstAr: "محمود",
    firstEn: "Mahmoud",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g3-4",
    gen: 3,
    fatherId: "g2-1",
    nameAr: "حسين مصطفى",
    nameEn: "Hussein Mustafa",
    firstAr: "حسين",
    firstEn: "Hussein",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g4-1",
    gen: 4,
    fatherId: "g3-1",
    nameAr: "هلال محمد",
    nameEn: "Hilal Muhammad",
    firstAr: "هلال",
    firstEn: "Hilal",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g4-2",
    gen: 4,
    fatherId: "g3-2",
    nameAr: "أحمد عبدالله",
    nameEn: "Ahmad Abdullah",
    firstAr: "أحمد",
    firstEn: "Ahmad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g4-3",
    gen: 4,
    fatherId: "g3-3",
    nameAr: "طه محمود",
    nameEn: "Taha Mahmoud",
    firstAr: "طه",
    firstEn: "Taha",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g4-4",
    gen: 4,
    fatherId: "g3-3",
    nameAr: "مطر محمود",
    nameEn: "Matar Mahmoud",
    firstAr: "مطر",
    firstEn: "Matar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g4-5",
    gen: 4,
    fatherId: "g3-4",
    nameAr: "عبدالقادر حسين",
    nameEn: "Abd al-Qadir Hussein",
    firstAr: "عبدالقادر",
    firstEn: "Abd al-Qadir",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g4-6",
    gen: 4,
    fatherId: "g3-4",
    nameAr: "ابراهيم حسين",
    nameEn: "Ibrahim Hussein",
    firstAr: "ابراهيم",
    firstEn: "Ibrahim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g5-1",
    gen: 5,
    fatherId: "g4-1",
    nameAr: "رجب هلال",
    nameEn: "Rajab Hilal",
    firstAr: "رجب",
    firstEn: "Rajab",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-2",
    gen: 5,
    fatherId: "g4-1",
    nameAr: "نظمي هلال",
    nameEn: "Nazmi Hilal",
    firstAr: "نظمي",
    firstEn: "Nazmi",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-3",
    gen: 5,
    fatherId: "g4-2",
    nameAr: "سليم أحمد",
    nameEn: "Salim Ahmad",
    firstAr: "سليم",
    firstEn: "Salim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-4",
    gen: 5,
    fatherId: "g4-4",
    nameAr: "عطاالله مطر",
    nameEn: "Ata Allah Matar",
    firstAr: "عطاالله",
    firstEn: "Ata Allah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-5",
    gen: 5,
    fatherId: "g4-4",
    nameAr: "حمدالله مطر",
    nameEn: "Hamd Allah Matar",
    firstAr: "حمدالله",
    firstEn: "Hamd Allah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-6",
    gen: 5,
    fatherId: "g4-4",
    nameAr: "عطية مطر",
    nameEn: "Atiyya Matar",
    firstAr: "عطية",
    firstEn: "Atiyya",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-7",
    gen: 5,
    fatherId: "g4-5",
    nameAr: "صبري عبدالقادر",
    nameEn: "Sabri Abd al-Qadir",
    firstAr: "صبري",
    firstEn: "Sabri",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-8",
    gen: 5,
    fatherId: "g4-5",
    nameAr: "حسين عبدالقادر",
    nameEn: "Hussein Abd al-Qadir",
    firstAr: "حسين",
    firstEn: "Hussein",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g5-9",
    gen: 5,
    fatherId: "g4-6",
    nameAr: "خليل ابراهيم",
    nameEn: "Khalil Ibrahim",
    firstAr: "خليل",
    firstEn: "Khalil",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g6-1",
    gen: 6,
    fatherId: "g5-1",
    nameAr: "ابراهيم رجب",
    nameEn: "Ibrahim Rajab",
    firstAr: "ابراهيم",
    firstEn: "Ibrahim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-2",
    gen: 6,
    fatherId: "g5-1",
    nameAr: "شعيب رجب",
    nameEn: "Shuayb Rajab",
    firstAr: "شعيب",
    firstEn: "Shuayb",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-3",
    gen: 6,
    fatherId: "g5-2",
    nameAr: "جلال نظمي",
    nameEn: "Jalal Nazmi",
    firstAr: "جلال",
    firstEn: "Jalal",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-4",
    gen: 6,
    fatherId: "g5-3",
    nameAr: "محمد سليم",
    nameEn: "Muhammad Salim",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-5",
    gen: 6,
    fatherId: "g5-4",
    nameAr: "فتحي عطاالله",
    nameEn: "Fathi Ata Allah",
    firstAr: "فتحي",
    firstEn: "Fathi",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-6",
    gen: 6,
    fatherId: "g5-4",
    nameAr: "يوسف عطاالله",
    nameEn: "Yousef Ata Allah",
    firstAr: "يوسف",
    firstEn: "Yousef",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-7",
    gen: 6,
    fatherId: "g5-4",
    nameAr: "محمود عطاالله",
    nameEn: "Mahmoud Ata Allah",
    firstAr: "محمود",
    firstEn: "Mahmoud",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-8",
    gen: 6,
    fatherId: "g5-6",
    nameAr: "محمد عطية",
    nameEn: "Muhammad Atiyya",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-9",
    gen: 6,
    fatherId: "g5-6",
    nameAr: "مصطفى عطية",
    nameEn: "Mustafa Atiyya",
    firstAr: "مصطفى",
    firstEn: "Mustafa",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-10",
    gen: 6,
    fatherId: "g5-6",
    nameAr: "ضرار عطية",
    nameEn: "Dirar Atiyya",
    firstAr: "ضرار",
    firstEn: "Dirar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-11",
    gen: 6,
    fatherId: "g5-7",
    nameAr: "معروف صبري",
    nameEn: "Maarouf Sabri",
    firstAr: "معروف",
    firstEn: "Maarouf",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-12",
    gen: 6,
    fatherId: "g5-8",
    nameAr: "حسن حسين",
    nameEn: "Hasan Hussein",
    firstAr: "حسن",
    firstEn: "Hasan",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-13",
    gen: 6,
    fatherId: "g5-9",
    nameAr: "شكري خليل",
    nameEn: "Shukri Khalil",
    firstAr: "شكري",
    firstEn: "Shukri",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g6-14",
    gen: 6,
    fatherId: "g5-9",
    nameAr: "عبداللطيف خليل",
    nameEn: "Abd al-Latif Khalil",
    firstAr: "عبداللطيف",
    firstEn: "Abd al-Latif",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g7-1",
    gen: 7,
    fatherId: "g6-1",
    nameAr: "عارف ابراهيم",
    nameEn: "Arif Ibrahim",
    firstAr: "عارف",
    firstEn: "Arif",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-2",
    gen: 7,
    fatherId: "g6-1",
    nameAr: "محمد ابراهيم",
    nameEn: "Muhammad Ibrahim",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-3",
    gen: 7,
    fatherId: "g6-2",
    nameAr: "شعبان شعيب",
    nameEn: "Shaban Shuayb",
    firstAr: "شعبان",
    firstEn: "Shaban",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-4",
    gen: 7,
    fatherId: "g6-2",
    nameAr: "زهير شعيب",
    nameEn: "Zuhayr Shuayb",
    firstAr: "زهير",
    firstEn: "Zuhayr",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-5",
    gen: 7,
    fatherId: "g6-2",
    nameAr: "زاهي شعيب",
    nameEn: "Zahi Shuayb",
    firstAr: "زاهي",
    firstEn: "Zahi",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-6",
    gen: 7,
    fatherId: "g6-3",
    nameAr: "أحمد جلال",
    nameEn: "Ahmad Jalal",
    firstAr: "أحمد",
    firstEn: "Ahmad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-7",
    gen: 7,
    fatherId: "g6-4",
    nameAr: "أحمد محمد",
    nameEn: "Ahmad Muhammad",
    firstAr: "أحمد",
    firstEn: "Ahmad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-8",
    gen: 7,
    fatherId: "g6-5",
    nameAr: "ناظم فتحي",
    nameEn: "Nazim Fathi",
    firstAr: "ناظم",
    firstEn: "Nazim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-9",
    gen: 7,
    fatherId: "g6-5",
    nameAr: "باسم فتحي",
    nameEn: "Basim Fathi",
    firstAr: "باسم",
    firstEn: "Basim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-10",
    gen: 7,
    fatherId: "g6-5",
    nameAr: "حازم فتحي",
    nameEn: "Hazim Fathi",
    firstAr: "حازم",
    firstEn: "Hazim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-11",
    gen: 7,
    fatherId: "g6-5",
    nameAr: "مطر فتحي",
    nameEn: "Matar Fathi",
    firstAr: "مطر",
    firstEn: "Matar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-12",
    gen: 7,
    fatherId: "g6-5",
    nameAr: "حاتم فتحي",
    nameEn: "Hatim Fathi",
    firstAr: "حاتم",
    firstEn: "Hatim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-13",
    gen: 7,
    fatherId: "g6-6",
    nameAr: "ثائر يوسف",
    nameEn: "Thaer Yousef",
    firstAr: "ثائر",
    firstEn: "Thaer",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-14",
    gen: 7,
    fatherId: "g6-6",
    nameAr: "أشرف يوسف",
    nameEn: "Ashraf Yousef",
    firstAr: "أشرف",
    firstEn: "Ashraf",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-15",
    gen: 7,
    fatherId: "g6-7",
    nameAr: "نشأت محمود",
    nameEn: "Nashat Mahmoud",
    firstAr: "نشأت",
    firstEn: "Nashat",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-16",
    gen: 7,
    fatherId: "g6-7",
    nameAr: "نهاد محمود",
    nameEn: "Nihad Mahmoud",
    firstAr: "نهاد",
    firstEn: "Nihad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-17",
    gen: 7,
    fatherId: "g6-7",
    nameAr: "جهاد محمود",
    nameEn: "Jihad Mahmoud",
    firstAr: "جهاد",
    firstEn: "Jihad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-18",
    gen: 7,
    fatherId: "g6-8",
    nameAr: "هيثم محمد",
    nameEn: "Haytham Muhammad",
    firstAr: "هيثم",
    firstEn: "Haytham",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-19",
    gen: 7,
    fatherId: "g6-10",
    nameAr: "علاء ضرار",
    nameEn: "Alaa Dirar",
    firstAr: "علاء",
    firstEn: "Alaa",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-20",
    gen: 7,
    fatherId: "g6-10",
    nameAr: "بهاء ضرار",
    nameEn: "Baha Dirar",
    firstAr: "بهاء",
    firstEn: "Baha",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-21",
    gen: 7,
    fatherId: "g6-10",
    nameAr: "نزار ضرار",
    nameEn: "Nizar Dirar",
    firstAr: "نزار",
    firstEn: "Nizar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-22",
    gen: 7,
    fatherId: "g6-11",
    nameAr: "صندري معروف",
    nameEn: "Sandry Maarouf",
    firstAr: "صندري",
    firstEn: "Sandry",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-23",
    gen: 7,
    fatherId: "g6-12",
    nameAr: "علي حسن",
    nameEn: "Ali Hasan",
    firstAr: "علي",
    firstEn: "Ali",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-24",
    gen: 7,
    fatherId: "g6-13",
    nameAr: "خليل شكري",
    nameEn: "Khalil Shukri",
    firstAr: "خليل",
    firstEn: "Khalil",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g7-25",
    gen: 7,
    fatherId: "g6-14",
    nameAr: "لطفي عبداللطيف",
    nameEn: "Lutfi Abd al-Latif",
    firstAr: "لطفي",
    firstEn: "Lutfi",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g8-1",
    gen: 8,
    fatherId: "g7-1",
    nameAr: "لؤي عارف",
    nameEn: "Luay Arif",
    firstAr: "لؤي",
    firstEn: "Luay",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-2",
    gen: 8,
    fatherId: "g7-2",
    nameAr: "لؤي محمد",
    nameEn: "Luay Muhammad",
    firstAr: "لؤي",
    firstEn: "Luay",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-3",
    gen: 8,
    fatherId: "g7-3",
    nameAr: "محمد شعبان",
    nameEn: "Muhammad Shaban",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-4",
    gen: 8,
    fatherId: "g7-5",
    nameAr: "سعيد زاهي",
    nameEn: "Said Zahi",
    firstAr: "سعيد",
    firstEn: "Said",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-5",
    gen: 8,
    fatherId: "g7-6",
    nameAr: "مصطفى أحمد",
    nameEn: "Mustafa Ahmad",
    firstAr: "مصطفى",
    firstEn: "Mustafa",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-6",
    gen: 8,
    fatherId: "g7-7",
    nameAr: "خلف أحمد",
    nameEn: "Khalaf Ahmad",
    firstAr: "خلف",
    firstEn: "Khalaf",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-7",
    gen: 8,
    fatherId: "g7-8",
    nameAr: "محمد ناظم",
    nameEn: "Muhammad Nazim",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-8",
    gen: 8,
    fatherId: "g7-8",
    nameAr: "عطاالله ناظم",
    nameEn: "Ata Allah Nazim",
    firstAr: "عطاالله",
    firstEn: "Ata Allah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-9",
    gen: 8,
    fatherId: "g7-8",
    nameAr: "أنس ناظم",
    nameEn: "Anas Nazim",
    firstAr: "أنس",
    firstEn: "Anas",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-10",
    gen: 8,
    fatherId: "g7-9",
    nameAr: "بسام باسم",
    nameEn: "Bassam Basim",
    firstAr: "بسام",
    firstEn: "Bassam",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-11",
    gen: 8,
    fatherId: "g7-9",
    nameAr: "خالد باسم",
    nameEn: "Khalid Basim",
    firstAr: "خالد",
    firstEn: "Khalid",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-12",
    gen: 8,
    fatherId: "g7-9",
    nameAr: "نصرالله باسم",
    nameEn: "Nasr Allah Basim",
    firstAr: "نصرالله",
    firstEn: "Nasr Allah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-13",
    gen: 8,
    fatherId: "g7-9",
    nameAr: "حمدالله باسم",
    nameEn: "Hamd Allah Basim",
    firstAr: "حمدالله",
    firstEn: "Hamd Allah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-14",
    gen: 8,
    fatherId: "g7-10",
    nameAr: "مجد حازم",
    nameEn: "Majd Hazim",
    firstAr: "مجد",
    firstEn: "Majd",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-15",
    gen: 8,
    fatherId: "g7-10",
    nameAr: "آدم حازم",
    nameEn: "Adam Hazim",
    firstAr: "آدم",
    firstEn: "Adam",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-16",
    gen: 8,
    fatherId: "g7-11",
    nameAr: "لؤي مطر",
    nameEn: "Luay Matar",
    firstAr: "لؤي",
    firstEn: "Luay",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-17",
    gen: 8,
    fatherId: "g7-11",
    nameAr: "محمد مطر",
    nameEn: "Muhammad Matar",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-18",
    gen: 8,
    fatherId: "g7-12",
    nameAr: "أحمد حاتم",
    nameEn: "Ahmad Hatim",
    firstAr: "أحمد",
    firstEn: "Ahmad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-19",
    gen: 8,
    fatherId: "g7-12",
    nameAr: "قيس حاتم",
    nameEn: "Qays Hatim",
    firstAr: "قيس",
    firstEn: "Qays",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-20",
    gen: 8,
    fatherId: "g7-13",
    nameAr: "مجدي ثائر",
    nameEn: "Majdi Thaer",
    firstAr: "مجدي",
    firstEn: "Majdi",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-21",
    gen: 8,
    fatherId: "g7-13",
    nameAr: "يوسف ثائر",
    nameEn: "Yousef Thaer",
    firstAr: "يوسف",
    firstEn: "Yousef",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-22",
    gen: 8,
    fatherId: "g7-13",
    nameAr: "مصطفى ثائر",
    nameEn: "Mustafa Thaer",
    firstAr: "مصطفى",
    firstEn: "Mustafa",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-23",
    gen: 8,
    fatherId: "g7-14",
    nameAr: "ليث أشرف",
    nameEn: "Layth Ashraf",
    firstAr: "ليث",
    firstEn: "Layth",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-24",
    gen: 8,
    fatherId: "g7-14",
    nameAr: "أسامة أشرف",
    nameEn: "Osama Ashraf",
    firstAr: "أسامة",
    firstEn: "Osama",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-25",
    gen: 8,
    fatherId: "g7-14",
    nameAr: "محمد أشرف",
    nameEn: "Muhammad Ashraf",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-26",
    gen: 8,
    fatherId: "g7-14",
    nameAr: "كريم أشرف",
    nameEn: "Karim Ashraf",
    firstAr: "كريم",
    firstEn: "Karim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-27",
    gen: 8,
    fatherId: "g7-15",
    nameAr: "طارق نشأت",
    nameEn: "Tariq Nashat",
    firstAr: "طارق",
    firstEn: "Tariq",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-28",
    gen: 8,
    fatherId: "g7-15",
    nameAr: "محمود نشأت",
    nameEn: "Mahmoud Nashat",
    firstAr: "محمود",
    firstEn: "Mahmoud",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-29",
    gen: 8,
    fatherId: "g7-15",
    nameAr: "يوسف نشأت",
    nameEn: "Yousef Nashat",
    firstAr: "يوسف",
    firstEn: "Yousef",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-30",
    gen: 8,
    fatherId: "g7-15",
    nameAr: "أحمد نشأت",
    nameEn: "Ahmad Nashat",
    firstAr: "أحمد",
    firstEn: "Ahmad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-31",
    gen: 8,
    fatherId: "g7-16",
    nameAr: "يزن نهاد",
    nameEn: "Yazan Nihad",
    firstAr: "يزن",
    firstEn: "Yazan",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-32",
    gen: 8,
    fatherId: "g7-16",
    nameAr: "مروان نهاد",
    nameEn: "Marwan Nihad",
    firstAr: "مروان",
    firstEn: "Marwan",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-33",
    gen: 8,
    fatherId: "g7-17",
    nameAr: "عمار جهاد",
    nameEn: "Ammar Jihad",
    firstAr: "عمار",
    firstEn: "Ammar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-34",
    gen: 8,
    fatherId: "g7-17",
    nameAr: "بشار جهاد",
    nameEn: "Bashar Jihad",
    firstAr: "بشار",
    firstEn: "Bashar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-35",
    gen: 8,
    fatherId: "g7-17",
    nameAr: "محمد جهاد",
    nameEn: "Muhammad Jihad",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-36",
    gen: 8,
    fatherId: "g7-18",
    nameAr: "أسامة هيثم",
    nameEn: "Osama Haytham",
    firstAr: "أسامة",
    firstEn: "Osama",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-37",
    gen: 8,
    fatherId: "g7-18",
    nameAr: "محمد هيثم",
    nameEn: "Muhammad Haytham",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-38",
    gen: 8,
    fatherId: "g7-19",
    nameAr: "آدم علاء",
    nameEn: "Adam Alaa",
    firstAr: "آدم",
    firstEn: "Adam",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-39",
    gen: 8,
    fatherId: "g7-20",
    nameAr: "وليد بهاء",
    nameEn: "Walid Baha",
    firstAr: "وليد",
    firstEn: "Walid",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-40",
    gen: 8,
    fatherId: "g7-20",
    nameAr: "عبدالرحمن بهاء",
    nameEn: "Abd al-Rahman Baha",
    firstAr: "عبدالرحمن",
    firstEn: "Abd al-Rahman",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-41",
    gen: 8,
    fatherId: "g7-20",
    nameAr: "مصطفى بهاء",
    nameEn: "Mustafa Baha",
    firstAr: "مصطفى",
    firstEn: "Mustafa",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-42",
    gen: 8,
    fatherId: "g7-22",
    nameAr: "سميح صندري",
    nameEn: "Samih Sandry",
    firstAr: "سميح",
    firstEn: "Samih",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-43",
    gen: 8,
    fatherId: "g7-23",
    nameAr: "بدر علي",
    nameEn: "Badr Ali",
    firstAr: "بدر",
    firstEn: "Badr",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-44",
    gen: 8,
    fatherId: "g7-24",
    nameAr: "فرح خليل",
    nameEn: "Farah Khalil",
    firstAr: "فرح",
    firstEn: "Farah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g8-45",
    gen: 8,
    fatherId: "g7-25",
    nameAr: "علي لطفي",
    nameEn: "Ali Lutfi",
    firstAr: "علي",
    firstEn: "Ali",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g9-1",
    gen: 9,
    fatherId: "g8-1",
    nameAr: "ادريس لؤي",
    nameEn: "Idris Luay",
    firstAr: "ادريس",
    firstEn: "Idris",
    placeAr: "",
    placeEn: "",
    honorific: "",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-2",
    gen: 9,
    fatherId: "g8-2",
    nameAr: "نايف لؤي",
    nameEn: "Nayif Luay",
    firstAr: "نايف",
    firstEn: "Nayif",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-3",
    gen: 9,
    fatherId: "g8-3",
    nameAr: "عدنان محمد",
    nameEn: "Adnan Muhammad",
    firstAr: "عدنان",
    firstEn: "Adnan",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-4",
    gen: 9,
    fatherId: "g8-3",
    nameAr: "ابراهيم محمد",
    nameEn: "Ibrahim Muhammad",
    firstAr: "ابراهيم",
    firstEn: "Ibrahim",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-5",
    gen: 9,
    fatherId: "g8-4",
    nameAr: "عبدالرحمن سعيد",
    nameEn: "Abd al-Rahman Said",
    firstAr: "عبدالرحمن",
    firstEn: "Abd al-Rahman",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-6",
    gen: 9,
    fatherId: "g8-5",
    nameAr: "رياض مصطفى",
    nameEn: "Riyad Mustafa",
    firstAr: "رياض",
    firstEn: "Riyad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-7",
    gen: 9,
    fatherId: "g8-6",
    nameAr: "محمود خلف",
    nameEn: "Mahmoud Khalaf",
    firstAr: "محمود",
    firstEn: "Mahmoud",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-8",
    gen: 9,
    fatherId: "g8-11",
    nameAr: "أحمد خالد",
    nameEn: "Ahmad Khalid",
    firstAr: "أحمد",
    firstEn: "Ahmad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-9",
    gen: 9,
    fatherId: "g8-11",
    nameAr: "يوسف خالد",
    nameEn: "Yousef Khalid",
    firstAr: "يوسف",
    firstEn: "Yousef",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-10",
    gen: 9,
    fatherId: "g8-20",
    nameAr: "براء مجدي",
    nameEn: "Baraa Majdi",
    firstAr: "براء",
    firstEn: "Baraa",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-11",
    gen: 9,
    fatherId: "g8-20",
    nameAr: "عمر مجدي",
    nameEn: "Umar Majdi",
    firstAr: "عمر",
    firstEn: "Umar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-12",
    gen: 9,
    fatherId: "g8-23",
    nameAr: "أشرف ليث",
    nameEn: "Ashraf Layth",
    firstAr: "أشرف",
    firstEn: "Ashraf",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-13",
    gen: 9,
    fatherId: "g8-42",
    nameAr: "سمير سميح",
    nameEn: "Samir Samih",
    firstAr: "سمير",
    firstEn: "Samir",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-14",
    gen: 9,
    fatherId: "g8-43",
    nameAr: "ربحي بدر",
    nameEn: "Ribhi Badr",
    firstAr: "ربحي",
    firstEn: "Ribhi",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-15",
    gen: 9,
    fatherId: "g8-44",
    nameAr: "فرحات فرح",
    nameEn: "Farhat Farah",
    firstAr: "فرحات",
    firstEn: "Farhat",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g9-16",
    gen: 9,
    fatherId: "g8-45",
    nameAr: "داوود علي",
    nameEn: "Dawud Ali",
    firstAr: "داوود",
    firstEn: "Dawud",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g10-1",
    gen: 10,
    fatherId: "g9-2",
    nameAr: "سامي نايف",
    nameEn: "Sami Nayif",
    firstAr: "سامي",
    firstEn: "Sami",
    placeAr: "",
    placeEn: "",
    honorific: "",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-2",
    gen: 10,
    fatherId: "g9-3",
    nameAr: "سمير عدنان",
    nameEn: "Samir Adnan",
    firstAr: "سمير",
    firstEn: "Samir",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-3",
    gen: 10,
    fatherId: "g9-4",
    nameAr: "نطاطا ابراهيم",
    nameEn: "Natata Ibrahim",
    firstAr: "نطاطا",
    firstEn: "Natata",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-4",
    gen: 10,
    fatherId: "g9-5",
    nameAr: "رجب عبدالرحمن",
    nameEn: "Rajab Abd al-Rahman",
    firstAr: "رجب",
    firstEn: "Rajab",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-5",
    gen: 10,
    fatherId: "g9-6",
    nameAr: "جمال رياض",
    nameEn: "Jamal Riyad",
    firstAr: "جمال",
    firstEn: "Jamal",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-6",
    gen: 10,
    fatherId: "g9-7",
    nameAr: "عبدالحميد محمود",
    nameEn: "Abd al-Hamid Mahmoud",
    firstAr: "عبدالحميد",
    firstEn: "Abd al-Hamid",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-7",
    gen: 10,
    fatherId: "g9-13",
    nameAr: "ثابت سمير",
    nameEn: "Thabit Samir",
    firstAr: "ثابت",
    firstEn: "Thabit",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-8",
    gen: 10,
    fatherId: "g9-14",
    nameAr: "عمر ربحي",
    nameEn: "Umar Ribhi",
    firstAr: "عمر",
    firstEn: "Umar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g10-9",
    gen: 10,
    fatherId: "g9-16",
    nameAr: "جودات داوود",
    nameEn: "Jawdat Dawud",
    firstAr: "جودات",
    firstEn: "Jawdat",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g11-1",
    gen: 11,
    fatherId: "g10-2",
    nameAr: "محمد سمير",
    nameEn: "Muhammad Samir",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g11-2",
    gen: 11,
    fatherId: "g10-4",
    nameAr: "محمد رجب",
    nameEn: "Muhammad Rajab",
    firstAr: "محمد",
    firstEn: "Muhammad",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g11-3",
    gen: 11,
    fatherId: "g10-5",
    nameAr: "شوقي جمال",
    nameEn: "Shawqi Jamal",
    firstAr: "شوقي",
    firstEn: "Shawqi",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g11-4",
    gen: 11,
    fatherId: "g10-6",
    nameAr: "يوسف عبدالحميد",
    nameEn: "Yousef Abd al-Hamid",
    firstAr: "يوسف",
    firstEn: "Yousef",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g11-5",
    gen: 11,
    fatherId: "g10-7",
    nameAr: "مدحت ثابت",
    nameEn: "Medhat Thabit",
    firstAr: "مدحت",
    firstEn: "Medhat",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g11-6",
    gen: 11,
    fatherId: "g10-8",
    nameAr: "نائل عمر",
    nameEn: "Nael Umar",
    firstAr: "نائل",
    firstEn: "Nael",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g11-7",
    gen: 11,
    fatherId: "g10-9",
    nameAr: "جودة جودات",
    nameEn: "Jawda Jawdat",
    firstAr: "جودة",
    firstEn: "Joud",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g12-1",
    gen: 12,
    fatherId: "g11-3",
    nameAr: "عمر شوقي",
    nameEn: "Umar Shawqi",
    firstAr: "عمر",
    firstEn: "Umar",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g12-2",
    gen: 12,
    fatherId: "g11-4",
    nameAr: "منذر يوسف",
    nameEn: "Mundhir Yousef",
    firstAr: "منذر",
    firstEn: "Mundhir",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
  {
    id: "g12-3",
    gen: 12,
    fatherId: "g11-7",
    nameAr: "سميح جودة",
    nameEn: "Samih Joud",
    firstAr: "سميح",
    firstEn: "Samih",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g13-1",
    gen: 13,
    fatherId: "g12-1",
    nameAr: "خالد عمر",
    nameEn: "Khalid Umar",
    firstAr: "خالد",
    firstEn: "Khalid",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g14-1",
    gen: 14,
    fatherId: "g13-1",
    nameAr: "عبدالله خالد",
    nameEn: "Abdullah Khalid",
    firstAr: "عبدالله",
    firstEn: "Abdullah",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g15-1",
    gen: 15,
    fatherId: "g14-1",
    nameAr: "يوسف عبدالله",
    nameEn: "Yousef Abdullah",
    firstAr: "يوسف",
    firstEn: "Yousef",
    placeAr: "",
    placeEn: "",
    honorific: "رحمه الله",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },

  {
    id: "g16-1",
    gen: 16,
    fatherId: "g15-1",
    nameAr: "بنيامين يوسف",
    nameEn: "Binyamin Yousef",
    firstAr: "بنيامين",
    firstEn: "Binyamin",
    placeAr: "",
    placeEn: "",
    honorific: "",
    bioAr: "",
    bioEn: "",
    sourcesEn: [],
    verified: true,
  },
]

const people: Person[] = raw.map(p => ({
  ...p,
  monogramAr: p.firstAr[0],
  monogramEn: p.firstEn[0],
}))

const byId: Record<string, Person> = Object.fromEntries(people.map(p => [p.id, p]))

const childrenOf: Record<string, string[]> = Object.fromEntries(people.map(p => [p.id, [] as string[]]))
people.forEach(p => { if (p.fatherId) childrenOf[p.fatherId].push(p.id) })

const byGen: Record<number, Person[]> = {}
people.forEach(p => { (byGen[p.gen] ??= []).push(p) })
const generations = Object.keys(byGen).map(Number).sort((a, b) => a - b)

function ancestors(id: string): string[] {
  const out: string[] = []
  let cur: Person | undefined = byId[id]
  while (cur) { out.push(cur.id); cur = cur.fatherId ? byId[cur.fatherId] : undefined }
  return out
}

function relationship(aId: string, bId: string): RelResult | null {
  if (!byId[aId] || !byId[bId]) return null
  const aAnc = ancestors(aId)
  const bAnc = ancestors(bId)
  const bSet = new Set(bAnc)
  let lca: string | null = null
  for (const x of aAnc) { if (bSet.has(x)) { lca = x; break } }
  if (!lca) return null
  const aPath = aAnc.slice(0, aAnc.indexOf(lca) + 1)
  const bPath = bAnc.slice(0, bAnc.indexOf(lca) + 1)
  return { lca, aPath, bPath, aSteps: aPath.length - 1, bSteps: bPath.length - 1 }
}

function descendantCount(id: string): number {
  let n = 1
  for (const c of childrenOf[id]) n += descendantCount(c)
  return n
}

function topBranches(atGen = generations[1] ?? generations[0]) {
  return (byGen[atGen] ?? [])
    .map(p => ({ p, count: descendantCount(p.id) }))
    .sort((a, b) => b.count - a.count)
}

function stats(): Stats {
  const total = people.length
  const generationCount = generations.length
  const perGen = generations.map(g => ({ gen: g, count: byGen[g].length }))
  const fathers = people.filter(p => childrenOf[p.id].length > 0)
  const avgChildren = fathers.length
    ? fathers.reduce((s, p) => s + childrenOf[p.id].length, 0) / fathers.length
    : 0
  const verified = people.filter(p => p.verified).length
  return {
    total, generationCount, perGen, avgChildren,
    fathersCount: fathers.length, verified,
  }
}

export const data: KarajahData = {
  people, byId, byGen, generations, childrenOf,
  ancestors, relationship, descendantCount, topBranches, stats,
  root: people.find(p => p.fatherId === null)!,
}

export function getSubtree(rootId: string): KarajahData {
  const ids = new Set<string>()
  const q = [rootId]
  while (q.length) {
    const id = q.shift()!
    ids.add(id)
    for (const c of childrenOf[id] ?? []) q.push(c)
  }

  const sp = people.filter(p => ids.has(p.id))
  const sById: Record<string, Person> = Object.fromEntries(sp.map(p => [p.id, p]))
  const sChildrenOf: Record<string, string[]> = Object.fromEntries(
    sp.map(p => [p.id, (childrenOf[p.id] ?? []).filter(c => ids.has(c))])
  )
  const sByGen: Record<number, Person[]> = {}
  sp.forEach(p => { (sByGen[p.gen] ??= []).push(p) })
  const sGens = Object.keys(sByGen).map(Number).sort((a, b) => a - b)

  function sAncestors(id: string): string[] {
    const out: string[] = []
    let cur: Person | undefined = sById[id]
    while (cur) { out.push(cur.id); cur = cur.fatherId && ids.has(cur.fatherId) ? sById[cur.fatherId] : undefined }
    return out
  }

  function sRelationship(aId: string, bId: string): RelResult | null {
    if (!sById[aId] || !sById[bId]) return null
    const aAnc = sAncestors(aId)
    const bAnc = sAncestors(bId)
    const bSet = new Set(bAnc)
    let lca: string | null = null
    for (const x of aAnc) { if (bSet.has(x)) { lca = x; break } }
    if (!lca) return null
    const aPath = aAnc.slice(0, aAnc.indexOf(lca) + 1)
    const bPath = bAnc.slice(0, bAnc.indexOf(lca) + 1)
    return { lca, aPath, bPath, aSteps: aPath.length - 1, bSteps: bPath.length - 1 }
  }

  function sDescendantCount(id: string): number {
    let n = 1
    for (const c of sChildrenOf[id] ?? []) n += sDescendantCount(c)
    return n
  }

  function sTopBranches(atGen = sGens[1] ?? sGens[0]) {
    return (sByGen[atGen] ?? [])
      .map(p => ({ p, count: sDescendantCount(p.id) }))
      .sort((a, b) => b.count - a.count)
  }

  function sStats(): Stats {
    const total = sp.length
    const generationCount = sGens.length
    const perGen = sGens.map(g => ({ gen: g, count: sByGen[g].length }))
    const fathers = sp.filter(p => sChildrenOf[p.id].length > 0)
    const avgChildren = fathers.length
      ? fathers.reduce((s, p) => s + sChildrenOf[p.id].length, 0) / fathers.length
      : 0
    const verified = sp.filter(p => p.verified).length
    return {
      total, generationCount, perGen, avgChildren,
      fathersCount: fathers.length, verified,
    }
  }

  return {
    people: sp, byId: sById, byGen: sByGen, generations: sGens,
    childrenOf: sChildrenOf, ancestors: sAncestors,
    relationship: sRelationship, descendantCount: sDescendantCount,
    topBranches: sTopBranches, stats: sStats,
    root: sById[rootId],
  }
}
